@startuml 
sprite $FFICO028 [18x18/16] { 
FFFFFFFFEEFFFFFFFF
FFFFFFFEFFEFFFFFFF
FFFFFFEF7AFFFFFFFF
FFFFFFD9339FFDFFFF
FFFFFDF1725BBFEFFF
FFFFDF53996485FDFF
FFFFCF30B66114AEFF
FFFFCF30526115AEFF
FFFFDD51116375FDFF
FFFFFF8A10F6BFEFFF
FFFFB56510B7FDFFFF
FFFE93132297FFFFFF
FFFD930486A8FFFFFF
FFFFB4407889FFFFFF
FFFFFF825A6AFFFFFF
FFFFFDFFDCEFFFFFFF
FFFFFFECFFFFFFFFFF
FFFFFFFFFFFFFFFFFF
} 
@enduml 
