@startuml 
sprite $FFICO044 [18x18/16] { 
FFFFFFFFFFFFFFFFFF
FFFFFFFEEEFFFFFFFF
FFFEDFFFFFFFEDFFFF
FFFFFEE877CEFFFFFF
FEF85DF422BF85FDFF
FEF72E14FF0763FCFF
FFFFFF239618FFFFFF
FEFA13A846D724EDFF
FFEC4525653328DFFF
FFFF9335F3536FFFFF
FEF67B420136F5BFFF
FDF106F756BF30AFEF
FDF4002D99B201BEFF
FFEF201D00D105FDFF
FFC9FBBB88BFA9AEFF
FFDDEFFFFFFFFFCFFF
FFFFFEEFEEFFEEFFFF
FFFFFFFFFFFFFFFFFF
} 
@enduml 
