@startuml 
sprite $WINSE004 [18x18/16] { 
FFFFFFFFFFFFFFFFFF
FFFFFFFFFECCCCEFFF
FFFFFFFFFFFFFFFFFF
FFFFFFFDF853248EEF
FFFFFFFCD620049DEF
FFFFFFFFF973457FDF
FFFFDE942128B66FDF
FFFFFF84002A458FDF
FFFEBB97455677AFEF
FEFA41018B75FFFFFF
FEF95102A548BDEFFF
FEFA3666499BEFFFFF
FEFA28785CFFFFFFFF
FEFA36138ADEFFFFFF
FFFDBCABCEFFFFFFFF
FFFFFFFFFFFFFFFFFF
FFFFEFEEFFFFFFFFFF
FFFFFFFFFFFFFFFFFF
} 
@enduml 
